version: "2"
services:
  portfolio:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./packages/backend/env/.env.production
    environment:
      - VIRTUAL_HOST=akhilspillai.in
      - LETSENCRYPT_HOST=akhilspillai.in
